#!/usr/bin/env bash
# build.sh — Generates env-config.js from environment variables.
# Run by Vercel at build time via vercel.json buildCommand.

set -euo pipefail

API_URL="${ITACHI_API_URL:-}"
API_KEY="${ITACHI_API_KEY:-}"
REFRESH_INTERVAL="${ITACHI_REFRESH_INTERVAL:-10}"
ORCHESTRATOR_URL="${ITACHI_ORCHESTRATOR_URL:-http://localhost:3001}"

cat > env-config.js <<EOF
// Auto-generated by build.sh — do not edit manually
window.__ITACHI_ENV__ = {
  apiUrl: "${API_URL}",
  apiKey: "${API_KEY}",
  refreshInterval: ${REFRESH_INTERVAL},
  orchestratorUrl: "${ORCHESTRATOR_URL}"
};
EOF

echo "env-config.js generated successfully"
